users:
    user1:
        password: $argon2id$v=19$m=65536,t=3,p=4$wpbDcr6eS9sxEP/AmMgxdQ$ybc13t8/mlhdm+wqSASzDiitlC7oZp4Rz/Jx9nxgYTM
        displayname: User
        email: authelia@authelia.com
        groups:
            - admins
            - dev
        given_name: ""
        middle_name: ""
        family_name: ""
        nickname: ""
        gender: ""
        birthdate: ""
        website: ""
        profile: ""
        picture: ""
        zoneinfo: ""
        locale: ""
        phone_number: ""
        phone_extension: ""
        disabled: false
        address: null
        extra: {}
